name: Build Docker image

on:
  pull_request:

permissions:
  contents: read

env:
  PHP_CURRENT: php82

jobs:
  build:
    strategy:
      matrix:
        os_base: ["el9"]
        php_base: ["php82", "php83"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t test-build-${{ matrix.os_base }}-${{ matrix.php_base }} -f ${{ matrix.os_base }}.dockerfile --build-arg="PHP_BASE=${{ matrix.php_base }}" --build-arg="PHP_CURRENT=${{ env.PHP_CURRENT }}" .
